GET http://localhost:3000/categories?is_deleted=false


###
GET http://localhost:3000/categories/3

###
POST http://localhost:3000/categories
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjg4NDU5MDYwLCJleHAiOjE2ODg1NDU0NjB9.rfEuXp4ltgCXwo5mERBatNbBog39CZXDpDlmHeBU5ms

{
  "name": "Salatlar"
}

###
PATCH http://localhost:3000/categories/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjg4NDU5MDYwLCJleHAiOjE2ODg1NDU0NjB9.rfEuXp4ltgCXwo5mERBatNbBog39CZXDpDlmHeBU5ms

{
  "name": "Salatlar"
}

###
DELETE http://localhost:3000/categories/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNjg4NDU5MDYwLCJleHAiOjE2ODg1NDU0NjB9.rfEuXp4ltgCXwo5mERBatNbBog39CZXDpDlmHeBU5ms